services:
  haproxy:
    image: haproxy:2.8
    ports:
      - "8080:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - fastapi
    networks:
      - app-network

  fastapi:
    build: ./fastapi
    expose:
      - "8000"
    volumes:
      - ./fastapi/certs:/app/certs:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
