[project]
name = "haproxy-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "python-json-logger>=3.3.0",
    "uvicorn>=0.34.3",
]
